//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.12 at 12:57:20 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.squilla.co.in/WebCrawlers", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.squill.og.crawler.model;
