//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.03 at 08:03:19 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/WebCrawlers", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.squill.og.crawler.model;
