//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.02 at 07:49:05 AM IST 
//


package com.squill.og.crawler.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WebCrawler complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WebCrawler">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contentHandler" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="scopeDef" type="{http://www.example.org/WebCrawlers}scopeDef" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="domainUrl" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="historyTracking" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="flushFrequency" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="thresholdFrequency" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WebCrawler", propOrder = {
    "name",
    "description",
    "contentHandler",
    "scopeDef"
})
public class WebCrawler {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String contentHandler;
    protected ScopeDef scopeDef;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "domainUrl", required = true)
    protected String domainUrl;
    @XmlAttribute(name = "historyTracking")
    protected Boolean historyTracking;
    @XmlAttribute(name = "flushFrequency")
    protected Integer flushFrequency;
    @XmlAttribute(name = "thresholdFrequency")
    protected Integer thresholdFrequency;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the contentHandler property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentHandler() {
        return contentHandler;
    }

    /**
     * Sets the value of the contentHandler property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentHandler(String value) {
        this.contentHandler = value;
    }

    /**
     * Gets the value of the scopeDef property.
     * 
     * @return
     *     possible object is
     *     {@link ScopeDef }
     *     
     */
    public ScopeDef getScopeDef() {
        return scopeDef;
    }

    /**
     * Sets the value of the scopeDef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScopeDef }
     *     
     */
    public void setScopeDef(ScopeDef value) {
        this.scopeDef = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the domainUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomainUrl() {
        return domainUrl;
    }

    /**
     * Sets the value of the domainUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomainUrl(String value) {
        this.domainUrl = value;
    }

    /**
     * Gets the value of the historyTracking property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHistoryTracking() {
        return historyTracking;
    }

    /**
     * Sets the value of the historyTracking property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHistoryTracking(Boolean value) {
        this.historyTracking = value;
    }

    /**
     * Gets the value of the flushFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFlushFrequency() {
        return flushFrequency;
    }

    /**
     * Sets the value of the flushFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFlushFrequency(Integer value) {
        this.flushFrequency = value;
    }

    /**
     * Gets the value of the thresholdFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getThresholdFrequency() {
        return thresholdFrequency;
    }

    /**
     * Sets the value of the thresholdFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setThresholdFrequency(Integer value) {
        this.thresholdFrequency = value;
    }

}
